# Generated by Django 5.1.1 on 2024-10-01 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCU', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regis',
            name='id_user',
            field=models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regis',
            name='is_done',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='regis',
            name='no_antrean',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='id_mcu_regis',
            field=models.ForeignKey(limit_choices_to={'is_done': 0}, on_delete=django.db.models.deletion.CASCADE, to='MCU.regis'),
        ),
    ]
