# Generated by Django 5.1.1 on 2024-09-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCU', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Laki-laki'), (2, 'Perempuan')], default=1),
        ),
    ]
