# Generated by Django 5.1.1 on 2024-09-18 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCU', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regis',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
