# Generated by Django 5.1.1 on 2024-09-19 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCU', '0005_regis_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
    ]
