# Generated by Django 5.1.1 on 2024-09-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCU', '0007_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regis',
            name='date',
        ),
        migrations.RemoveField(
            model_name='regis',
            name='no_antrean',
        ),
    ]
